spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop_db
    username: root
    password: 1234321
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true


  flyway:
    #baseline-on-migrate: true
    enabled: true
    user: root
    password: 1234321
    baseline-description: "init"
    baseline-version: 0